name: "kindohm (a.k.a. mike hodnick)"
description: "code and music blog"
author: "Mike Hodnick"
exclude: [README.md, CNAME]
paginate: 5
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title
imagesPath: "/images/"
gems: ["jekyll-paginate"]
