name: "blog. mike. hodnick."
description: "code and music"
author: "kindohm"
exclude: [README.md, CNAME]
paginate: 5
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title
markdown: redcarpet
imagesPath: "/images/"
gems: ["jekyll-paginate"]
